# Generated by Django 4.2.2 on 2023-12-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('cliente', models.CharField(max_length=100, null=True)),
                ('medio_pago_v', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia BANCOLOMBIA', 'Transferencia BANCOLOMBIA'), ('Transferencia NEQUI', 'Transferencia NEQUI')], max_length=255)),
                ('estado_pago_v', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=255)),
            ],
        ),
    ]
