# Generated by Django 4.2.2 on 2023-12-13 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura_ventas', '0001_initial'),
        ('carteras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartera',
            name='factura_v',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura_ventas.factura_venta'),
        ),
    ]
