# Generated by Django 4.2.2 on 2023-12-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0002_cartera_factura_v'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartera',
            name='fecha_facturacion',
            field=models.DateField(),
        ),
    ]
