# Generated by Django 4.2.2 on 2023-12-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('detalle_compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='producto_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
