# Generated by Django 4.2.2 on 2023-12-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_ventas', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='precio_producto',
        ),
    ]
