# Generated by Django 4.2.2 on 2023-12-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_imagen_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
    ]
