# Generated by Django 4.2.2 on 2023-12-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=150)),
                ('medio_pago_c', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Transferencia Bancaria', 'Transferencia Bancaria')], max_length=255)),
                ('estado_pago_c', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=255)),
                ('total_c', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
