# Generated by Django 4.2.2 on 2023-12-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField()),
                ('proveedor', models.CharField(max_length=100, null=True)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100, null=True)),
                ('medio_pago_c', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de Crédito', 'Tarjeta de Crédito'), ('Transferencia Bancaria', 'Transferencia Bancaria')], max_length=255)),
                ('estado_pago_c', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=255)),
                ('categoriaf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorias.categoria')),
                ('lote_f', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotes.lote')),
            ],
        ),
    ]
